version: '3.9'
services:
  db:
    image: postgres:16
    container_name: creditmanager_db
    environment:
      # Banco e usuário que vamos usar no Django .env
      POSTGRES_DB: creditmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # usa as mesmas credenciais acima
      test: ["CMD-SHELL", "pg_isready -U postgres -d creditmanager"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
