# Generated by Django 5.2.5 on 2025-09-03 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes_app', '0002_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='gastos/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='cartoes_app.gasto')),
            ],
        ),
    ]
