# Generated by Django 5.2.5 on 2025-09-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes_app', '0003_gastoanexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoanexo',
            name='arquivo',
            field=models.FileField(upload_to='gastos/'),
        ),
    ]
