# Generated by Django 5.2.5 on 2025-10-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes_app', '0003_gastoanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gastoanexo',
            name='arquivo',
            field=models.FileField(upload_to='gastos/'),
        ),
    ]
