# Generated by Django 5.2.5 on 2025-10-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes_app', '0004_alter_gastoanexo_arquivo'),
        ('cartoes_app', '0004_cartaocredito_saldo_atual_alter_gastoanexo_arquivo'),
    ]

    operations = [
    ]
